DROP TABLE IF EXISTS CBR_ACCOUNTING;
DROP TABLE IF EXISTS CBR_WORKER;
DROP TABLE IF EXISTS CBR_PROJECT;

CREATE TABLE CBR_PROJECT (
  id     INT AUTO_INCREMENT PRIMARY KEY,
  s_name VARCHAR(250) NOT NULL
);

CREATE TABLE CBR_WORKER (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  s_job         VARCHAR(250) NOT NULL,
  s_first_name  VARCHAR(250) NOT NULL,
  s_last_name   VARCHAR(250) NOT NULL,
  s_middle_name VARCHAR(250) NOT NULL
);

CREATE TABLE CBR_ACCOUNTING (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  project_id INT          NOT NULL,
  worker_id  INT          NOT NULL,
  s_task     VARCHAR(250) NOT NULL,
  d_date     DATE         NOT NULL,
  d_time     INT          NOT NULL
);

ALTER TABLE CBR_ACCOUNTING
  ADD CONSTRAINT FK_CBR_ACCOUNTING$PROJECT_ID FOREIGN KEY (PROJECT_ID)
REFERENCES CBR_PROJECT (ID);

ALTER TABLE CBR_ACCOUNTING
  ADD CONSTRAINT FK_CBR_ACCOUNTING$WORKER_ID FOREIGN KEY (WORKER_ID)
REFERENCES CBR_WORKER (ID);
